-- MySQL Script generated by MySQL Workbench
-- Sat Jan 19 15:44:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema phparc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phparc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phparc` DEFAULT CHARACTER SET utf8 ;
USE `phparc` ;

-- -----------------------------------------------------
-- Table `phparc`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phparc`.`language` (
  `id` VARCHAR(2) NOT NULL,
  `language` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phparc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phparc`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `password_reset` VARCHAR(100) NULL,
  `language_id` VARCHAR(2) NOT NULL,
  `authorization` VARCHAR(300) NULL,
  `createat` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`mail` ASC),
  INDEX `fk_user_language_idx` (`language_id` ASC),
  CONSTRAINT `fk_user_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `phparc`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `phparc`.`language`
-- -----------------------------------------------------
START TRANSACTION;
USE `phparc`;
INSERT INTO `phparc`.`language` (`id`, `language`) VALUES ('BR', 'PORTUGUÊS');
INSERT INTO `phparc`.`language` (`id`, `language`) VALUES ('EN', 'ENGLISH');
INSERT INTO `phparc`.`language` (`id`, `language`) VALUES ('ES', 'ESPANHOL');

COMMIT;

